### ISSUE TITLE
Conditional backoff

### ISSUE THREAD

**Issue by kavuri** [MathieuTurcotte/node-backoff#17]
This is more of a question than a bug.
I am trying to use backoff retries on conditional basis and have the following specific scenario to support.
In my usecase, for some conditions (like network timeout / server failure), I would want a retry of the function (using exponential backoff strategy) and in some other conditions (like wrong username/password), there should not be any retry, but call should just fail.
How can I have this conditional callback possible?
I am using backoff.call() API

**Comment by MathieuTurcotte** [comment]
We need to add something to configure determine whether the operation was successful or not. Right now, the library simply assumes that any error should lead to a retry which is not flexible.

One option is to have something like this.

```javascript
var call = backoff.call(authenticate, username, password, function(err, res) {
    ...
});

call.setRetryPredicate(function(err) { return err.isRetriable(); });
call.setStrategy(new backoff.ExponentialStrategy());
call.failAfter(10);
call.start();
```

Another option is to pass it as an argument to `backoff.call` directly.

```javascript
var call = backoff.call(authenticate, username, password, function(err, res) {
    ...
}, function(err) { return err.isRetriable(); });

call.setStrategy(new backoff.ExponentialStrategy());
call.failAfter(10);
call.start();
```

I tend to prefer the first option since it keep `backoff.call` relatively simple while making it easier for existing clients to opt into the behavior. It's also keeping it closer to a builder pattern towards which I want to move the library gradually. I'll give it a shot this weekend.

**Comment by MathieuTurcotte** [comment]
This change should enable you to achieve what you were looking for. I.e. it adds an API on the functional API to specify a predicate invoked to decide whether a given error is retriable or not. Give it a shot and let me know how it goes. I'll bundle that in an upcoming release in the coming week.

**Comment by kavuri** [comment]
Thanks, this seems to work

**Comment by Bazze** [comment]
When will this go out in a release? :)

**Comment by MathieuTurcotte** [comment]
Pushed w/ 2.5.0.

**Comment by Bazze** [comment]
Many thanks @MathieuTurcotte!
